name: Stage the app

on:
  pull_request:
    types: [labeled]

jobs:
  build:
    runs-on: ubuntu_latest
    if: contains(github.event.pull_request.labels.*.name, 'stage')
    steps:
      run: echo hello